<a href="https://colab.research.google.com/github/pr0fez/AI24-Programmering/blob/master/Exercises/03-for-statement-exercise.ipynb" target="_parent"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> &nbsp; to see hints and answers.

# for statement exercises

---
These are introductory exercises in Python with focus in **for** statement.

<p class = "alert alert-info" role="alert"><b>Remember</b> to use <b>descriptive variable names</b> in order to get readable code </p>

<p class = "alert alert-info" role="alert"><b>Remember</b> to format your answers in a neat way using <b>f-strings</b>

<p class = "alert alert-info" role="alert"><b>Remember</b> to format your input questions in a pedagogical way to guide the user

The number of stars (\*), (\*\*), (\*\*\*) denotes the difficulty level of the task

---

## 1. Count numbers (*)

Use a **for** statement to count from: 

&nbsp; a) &nbsp; -10 to 10 with one increment (*)

&nbsp; b) &nbsp; -10 to 10 with two increment (*)

<details>

<summary>Answer </summary>

```
a) -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9 10

b) -10  -8  -6  -4  -2  0  2  4  6  8  10
```

</details>

In [2]:
for i in range (-10, 11, 2):
    print(i)

-10
-8
-6
-4
-2
0
2
4
6
8
10

---
## 2. Arithmetic sum (*)
Use a **for** statement to compute the following sums: 

&nbsp; a) &nbsp; $\text{sum} = 1 + 2 + \ldots + 99+ 100$ (*)

&nbsp; b) &nbsp; $\text{sum} = 1 + 3 + 5 + \ldots + 97 + 99$ (*)

<details>

<summary>Answer </summary>

```
a) 1 + 2 + ... + 99 + 100 = 5050 

b) 1 + 3 + 5 +...+ 97 + 99 = 2500
```

</details>

In [7]:
sum = 0
for i in range (1,100):
    if i % 2 != 0:
        sum += i
print(sum)

2500

---
## 3. Multiplication table (*)
Use **for** statement(s) to:

&nbsp; a) &nbsp; print out the 6th multiplication table from 0 to 10 (*)

&nbsp; b) &nbsp; let the user input the **table**, **start** and **end** of the table. (*)

&nbsp; c) &nbsp; print out a full multiplication table from 0 to 10. (**)


<details>

<summary>Hint</summary>

c) Use nested for-loops, which means a for-loop in a for-loop. To format the table nicely, use **f-string**: 

```python
print(f"{number :4}", end = "")
```


</details>


<details>

<summary>Answer </summary>

a)
```
0 6 12 18 24 30 36 42 48 54 60
```

b) e.g. 

```
Which table are you interested in? 5
Specify start of table: 5
Specify end of table: 12

Your 5th multiplication table from 5 to 12: 25 30 35 40 45 50 55 60
```

c)

```
   0   0   0   0   0   0   0   0   0   0   0
   0   1   2   3   4   5   6   7   8   9  10
   0   2   4   6   8  10  12  14  16  18  20
   0   3   6   9  12  15  18  21  24  27  30
   0   4   8  12  16  20  24  28  32  36  40
   0   5  10  15  20  25  30  35  40  45  50
   0   6  12  18  24  30  36  42  48  54  60
   0   7  14  21  28  35  42  49  56  63  70
   0   8  16  24  32  40  48  56  64  72  80
   0   9  18  27  36  45  54  63  72  81  90
   0  10  20  30  40  50  60  70  80  90 100
```

</details>

In [ ]:
for i in range (0,11):
  print(i*6)

table=input("which table is your intrest: ")
start=input("where do you want to start: ")   
end=input("where do you want to end: ")
for i in range (int(start), int(end)+1):
  print (f"{table}th multiplication from {start} to {end} is: {int(table)*i}")
  
for i in range (0,10):
  for j in range (0,10):
    print (f"{i}*{j} end=" ", ")

0
6
12
18
24
30
36
42
48
54
60
5th multiplication from 5 to 12 is: 25
5th multiplication from 5 to 12 is: 30
5th multiplication from 5 to 12 is: 35
5th multiplication from 5 to 12 is: 40
5th multiplication from 5 to 12 is: 45
5th multiplication from 5 to 12 is: 50
5th multiplication from 5 to 12 is: 55
5th multiplication from 5 to 12 is: 60
0*0=0
0*1=0
0*2=0
0*3=0
0*4=0
0*5=0
0*6=0
0*7=0
0*8=0
0*9=0
1*0=0
1*1=1
1*2=2
1*3=3
1*4=4
1*5=5
1*6=6
1*7=7
1*8=8
1*9=9
2*0=0
2*1=2
2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
3*0=0
3*1=3
3*2=6
3*3=9
3*4=12
3*5=15
3*6=18
3*7=21
3*8=24
3*9=27
4*0=0
4*1=4
4*2=8
4*3=12
4*4=16
4*5=20
4*6=24
4*7=28
4*8=32
4*9=36
5*0=0
5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
6*0=0
6*1=6
6*2=12
6*3=18
6*4=24
6*5=30
6*6=36
6*7=42
6*8=48
6*9=54
7*0=0
7*1=7
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
8*0=0
8*1=8
8*2=16
8*3=24
8*4=32
8*5=40
8*6=48
8*7=56
8*8=64
8*9=72
9*0=0
9*1=9
9*2=18
9*3=27
9*4=36
9*5=45
9*6=54
9*7=63
9*8=72
9*9=81

---
## 4. Faculty (*)

Use a **for** statement to compute $n!$. 

$n! = 1\cdot2\cdot3\cdot\ldots\cdot(n-1)\cdot n $

Let the user input $n$.

--- 
## 5. Guess the number (*)

The computer thinks of a four-digit number. Start by creating a random four-digit number. Use **for** statement to figure out a correct guess

<br>
<details>

<summary>Answer </summary>

e.g.
```
The final guess is 8993
The computer number is 8993
```

</details>

---
## 6. Rice on chessboard (*)

In first square of the chessboard there is one grain of rice, in the second square there is two grains, in the third square there is four grains and so on. How many grains are there in the whole chessboard when all squares are filled using this pattern?

<img align="left" src="../assets/chessboard.png" width="300"/>

<details>

<summary>Answer</summary>

```
18446744073709551615 number of grains
```

</details>

---

pr0fez Giang

[LinkedIn][linkedIn_pr0fez]

[GitHub portfolio][github_portfolio]

[linkedIn_pr0fez]: https://www.linkedin.com/in/pr0fezgiang/
[github_portfolio]: https://github.com/pr0fez/Portfolio-pr0fez-Giang

---